# frontend/Dockerfile.dev
FROM node:16

WORKDIR /app
COPY package*.json ./

# Limpiar cache y reinstalar dependencias
RUN npm cache clean --force
RUN rm -rf node_modules package-lock.json
RUN npm install --legacy-peer-deps --force

COPY . .
EXPOSE 3000

# usa react-scripts dev server con hot-reload
CMD ["npm", "start"]
