services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=Gladiadorin12.
      - DB_NAME=inventario
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "3300:3300"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Gladiadorin12.
      MYSQL_DATABASE: inventario
      MYSQL_USER: inventario_user
      MYSQL_PASSWORD: Gladiadorin12.
    ports:
      - "3307:3306"
    volumes:
      - inventario-data:/var/lib/mysql           # datos persistentes
      - ./db/init:/docker-entrypoint-initdb.d     # scripts .sql de inicialización
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pGladiadorin12."]
      timeout: 20s
      retries: 10

volumes:
  inventario-data:
